### PR TITLE
Update SiteHelper.py

### PR DESCRIPTION
**Pull request by Am1nCmd**
adding platfrom windows on supported jailbreak

### CODE REVIEW

**Comment by mass1ve-err0r** [comment]
Would you also please explain how these jailbreaks support windows?

**Comment by Am1nCmd** [comment]
Yes. It can be sideloaded. Use altstore or sideloadly or something else.

Sent from my iPhone

On 5 Feb 2021, at 1.44 AM, Saadat <notifications@github.com> wrote:

﻿

Would you also please explain how these jailbreaks support windows?

**Comment by mass1ve-err0r** [comment]
Ah you marked them because of sideloading. 
The tags do not reflect that method since it's not native to the jailbreak utility, I should have clarified that more explicitly.

Thanks for your PR nevertheless, I'll make a general information about Sideloading!

**Comment by Am1nCmd** [comment]
So why those already marked on canijailbreak website? Is there native? So no

Sent from my iPhone

On 5 Feb 2021, at 8.21 AM, Saadat <notifications@github.com> wrote:

﻿

Ah you marked them because of sideloading.
The tags do not reflect that method since it's not native to the jailbreak utility, I should have clarified that more explicitly.

Thanks for your PR nevertheless, I'll make a general information about Sideloading!

**Comment by mass1ve-err0r** [comment]
(for example) Pangu has a windows + osx badge since they have clients for these platfoms, newer jailbreaks such as Odyssey are device-only, the installation method is not relevant here

EDIT 1:
small correction

**Comment by Am1nCmd** [comment]
Alright. Got it

Sent from my iPhone

On 5 Feb 2021, at 8.27 AM, Saadat <notifications@github.com> wrote:

﻿

(for example) Pangu have a windows + osx badge since they have clients for these platfoms, newer jailbreaks such as Odyssey are device-only, the installation method is not relevant here

**Pull request closed without merging**
